version: '3.9'
services:
    # jupyter-timeseries:
    #     image: jupyter/scipy-notebook:latest
    #     ports:
    #         - 8887:8888
    #     volumes:
    #         - ./notebooks-timeseries:/home/jovyan
    #         - ./data-timeseries:/home/jovyan/data
    #     environment:
    #         JUPYTER_ENABLE_LAB: "yes"
    #         command: >
    #             bash -c "pip install numpy plotly && start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
    # jupyter-llm:
    #     image: jupyter/scipy-notebook:latest
    #     ports:
    #         - 8889:8888
    #     volumes:
    #         - ./notebooks-llm:/home/jovyan
    #         - ./data-llm:/home/jovyan/data
    #     environment:
    #         JUPYTER_ENABLE_LAB: "yes"
    #         NVIDIA_VISIBLE_DEVICES: "all"
    #         command: >
    #             bash -c "pip install torch accelerate peft bitsandbytes transformers trl && start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"

    jupyter-llama:
        image: jupyter/scipy-notebook:latest
        ports:
            - 8888:8888
        volumes:
            - ./notebooks-llama:/home/jovyan
            - ./data-llm:/home/jovyan/data
        environment:
            JUPYTER_ENABLE_LAB: "yes"
            NVIDIA_VISIBLE_DEVICES: "all"
            command: >
                bash -c "python -m pip install huggingface_hub ipython "unsloth[colab] @ git+https://github.com/unslothai/unsloth.git" "unsloth[conda] @ git+https://github.com/unslothai/unsloth.git" && start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [ gpu ]
