version: '3.9'
services:
    jupyter:
        image: jupyter/scipy-notebook:latest
        ports:
            - 8888:8888
        volumes:
            - ./notebooks:/home/jovyan
            - ./data:/home/jovyan/data
        environment:
            JUPYTER_ENABLE_LAB: "yes"
            command: >
                bash -c "pip install numpy plotly && start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
